name = "devcard"
main = "src/index.ts"
compatibility_date = "2025-07-18"

[assets]
directory = "./dist"

[vars]
# Set your GitHub token as a secret: wrangler secret put GITHUB_TOKEN
# GITHUB_TOKEN = ""

[[kv_namespaces]]
binding = "CACHE"
id = "ee1f8586ea9e4fcfa28b82870a1a3550"
preview_id = "607a7597605c4984aae071103c16a817"
